### ISSUE TITLE
Use upstream freeopcua

### ISSUE THREAD

**Issue by cjue** [iirob/ros_opcua_communication#1]
Hi, thank you for your effort towards this project!

Is there a specific reason to reference your own fork of freeopcua instead of the upstream version?
My suggested patch would be this:

```
diff --git a/.gitmodules b/.gitmodules
index 9231295..798a59d 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,6 +1,6 @@
 [submodule "ros_opcua_impl_freeopcua/freeopcua"]
        path = ros_opcua_impl_freeopcua/freeopcua
-       url = git@github.com:iirob/freeopcua.git
+       url = https://github.com/FreeOpcUa/freeopcua.git
 [submodule "ros_opcua_impl_python_opcua/python-opcua"]
        path = ros_opcua_impl_python_opcua/python-opcua
        url = https://github.com/FreeOpcUa/python-opcua.git
```

Using the https version for the remote is better for machines without github ssh keys set up.

**Comment by destogl** [comment]
Hi,

yes this seams reasonable. Thanks!!

Can you create PR?

**Comment by cjue** [comment]
Done: https://github.com/iirob/ros_opcua_communication/pull/2 and https://github.com/iirob/ros_opcua_communication/pull/3
