### ISSUE TITLE
how to run the server and client correctly

### ISSUE THREAD

**Issue by gary-robotics** [iirob/ros_opcua_communication#10]
hi,I am a newer of opcua,and i download ur code,  compile correctly.but i don't know how to use it,i just roslaunch the server and client .can u help me how to run it correctly? thank u very much!

**Comment by destogl** [comment]
Hi @guorun198959, 

what do you want to do? what is your goal? This is just a mapper from OPC UA to ROS and opposite.

**Comment by gary-robotics** [comment]
I want to use ur mapper to convert my ros message to OPC UA(for Server) in PC-A,and there is another PC-B (OS is windows) to be a OPC UA client. The goal is to realize the communication between PC-A and PC-B.I have no idea,Can you give some advice? Thanks again!

**Comment by destogl** [comment]
you should start
```
roslaunch ros_opcua_commnication rosopcua.launch
```

After a few seconds (20-30, depending on number of topics) you will get OPC UA Server started. Than you can explore it using UaExpert. For windows client please see example applications in python_opcua repositry.
