### ISSUE TITLE
Documentation or Tutorials

### ISSUE THREAD

**Issue by ghost** [iirob/ros_opcua_communication#11]
Hello :)

since I couldn't find anything about it in this repository, I want to ask if there is some kind of documentation or tutorial on how to use your package.
For example: How do I send packages to a certain IP? How do I listen to a certain IP? When should I run rosopcua.launch and when should I run client.launch?

Thank you

**Comment by destogl** [comment]
Hi @ToRaVe ,

thank you for your interest in this package. Sorry not to answer earlier, but I was not available last week. I added in PR #12 getting started steps in each README.md file.

If is this sufficient information for you please close this issue, if not please comment how I can make it better :)

Thanks!

**Comment by destogl** [comment]
Everything is now merged in the main branch.

**Comment by ghost** [comment]
Thank you! I will have a look at it and see if I am able to work with it. It might take me some days since I just returned from vacation.
Have a nice day! :)
