### ISSUE TITLE
Not subscribe to a specific topic Bug

### ISSUE THREAD

**Issue by arianna003** [iirob/ros_opcua_communication#17]
Hi,
i'm using realsense ros node but crash with ua. 
in particular make this error in real sense rgbd node 
[ERROR] [1551974811.293646433]: cv_bridge exception: '[16UC1] is not a color format. but [bgr8] is. The conversion does not make sense'
[ERROR] [1551974811.339636344]: Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: 8UC1).
So how can I ignore the camera topics to opcua_communication in the python version? 
thanks

**Comment by destogl** [comment]
@arianna003 which version are you exactly using?

If you are using `kinetic-devel` branch than you can choose namespace for which OPC-UA structures wil be created. See [this file](https://github.com/iirob/ros_opcua_communication/blob/kinetic-devel/ros_opcua_impl_python_opcua/config/params.yaml)

**Comment by arianna003** [comment]
i use ros melodic and i want to select topic that he create, excluding camera topic that create problem.

**Comment by destogl** [comment]
You can define just a namespace of your topic.

Exclusion of topics is not possible, but only inclusion of specific namespaces. But this should also work for you.

**Comment by arianna003** [comment]
i have solved putting in ros_topic.py un if:

if str(self.name)== "/slam/pos" :
		rospy.loginfo(str(self.name))
		self._recursive_create_items(self.parent, idx, topic_name, topic_type, self.message_instance, True)
                 self._subscriber = rospy.Subscriber(self.name, self.message_class, self.message_callback)
		self._publisher = rospy.Publisher(self.name, self.message_class, queue_size=1)
		rospy.loginfo("Created ROS Topic with name: " + str(self.name))


now create only the specific topic that i need and exclude camera topic that create problem.

**Comment by destogl** [comment]
This is also an option. But you could do that also with `namespace ` parameter.
