### ISSUE TITLE
ROS2 compatibility

### ISSUE THREAD

**Issue by cwrx777** [iirob/ros_opcua_communication#20]
is this compatible with ROS2 eloquent?

**Comment by destogl** [comment]
Hi @cwrx777,

no this is only ROS1 version. If you would like to port it, I will gladly merge it here.

Best,
Denis

**Comment by lyndwyrm666** [comment]
https://github.com/lyndwyrm666/ros_opcua_communication

this works for dashing and foxy, in case its still relevant for you
